name: Deploy

on:
  push:
    branches:
      - main

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/odin-playground

            git fetch
            git reset --hard origin/main
            git submodule foreach git submodule init
            git submodule update --recursive

            ODIN=/home/ubuntu/odin/odin PORT=80 DB_HOST=${{ secrets.DB_HOST }} DB_USERNAME=${{ secrets.DB_USERNAME }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} GITHUB_AUTH_HEADER="${{ secrets._GITHUB_AUTH_HEADER }}" make
            sudo setcap CAP_NET_BIND_SERVICE=+eip /home/ubuntu/odin-playground/odin-playground

            sudo pkill supervisord
            supervisord -c supervisord.conf
