name: Deploy

on:
  push:
    branches:
      - main

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          debug: true
          script: |
            cd ~/odin-playground
            git pull

            ~/odin/odin build . -o:speed \
            -define:DB_HOST=${{ secrets.DB_HOST }} \
            -define:DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -define:DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -define:DB_NAME=odin-playground \
            -define:PORT=80

            sudo pkill supervisord
            sudo supervisord -c supervisord.conf
