name: Update Odin

on:
  workflow_dispatch:

concurrency: deploy

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH update
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/odin
            git pull --depth=1 --recurse-submodules
            make

            cd ~/odin-playground
            git pull --depth=1 --recurse-submodules
            ~/odin/odin build . -o:speed -define:ODIN="/home/ubuntu/odin/odin" -define:ODIN_VERSION_DETAILED="$(/home/ubuntu/odin/odin version)" -define:GITHUB_AUTH_HEADER="${{ secrets._GITHUB_AUTH_HEADER }}" -define:DB_HOST=${{ secrets.DB_HOST }} -define:DB_USERNAME=${{ secrets.DB_USERNAME }} -define:DB_PASSWORD=${{ secrets.DB_PASSWORD }} -define:DB_NAME=odin-playground -define:PORT=80
            sudo setcap CAP_NET_BIND_SERVICE=+eip /home/ubuntu/odin-playground/odin-playground
            sudo pkill supervisord
            sudo pkill odin
            supervisord -c supervisord.conf
