name: Update Odin image

on:
  schedule:
    - cron: "0 0 * * *" # Daily.

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH update
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/odin-playground
            sudo docker build --no-cache -t odin-playground:latest .
